/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface KryptandT {
        "name": string;
    }
    interface SelectLanguage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLKryptandTElement extends Components.KryptandT, HTMLStencilElement {
    }
    var HTMLKryptandTElement: {
        prototype: HTMLKryptandTElement;
        new (): HTMLKryptandTElement;
    };
    interface HTMLSelectLanguageElement extends Components.SelectLanguage, HTMLStencilElement {
    }
    var HTMLSelectLanguageElement: {
        prototype: HTMLSelectLanguageElement;
        new (): HTMLSelectLanguageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "kryptand-t": HTMLKryptandTElement;
        "select-language": HTMLSelectLanguageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface KryptandT {
        "name"?: string;
    }
    interface SelectLanguage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "kryptand-t": KryptandT;
        "select-language": SelectLanguage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "kryptand-t": LocalJSX.KryptandT & JSXBase.HTMLAttributes<HTMLKryptandTElement>;
            "select-language": LocalJSX.SelectLanguage & JSXBase.HTMLAttributes<HTMLSelectLanguageElement>;
        }
    }
}
