/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface HomePage {
    }
    interface KryptandT {
        "name": string;
        "value": any;
    }
    interface SelectLanguage {
    }
    interface TestPage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLKryptandTElement extends Components.KryptandT, HTMLStencilElement {
    }
    var HTMLKryptandTElement: {
        prototype: HTMLKryptandTElement;
        new (): HTMLKryptandTElement;
    };
    interface HTMLSelectLanguageElement extends Components.SelectLanguage, HTMLStencilElement {
    }
    var HTMLSelectLanguageElement: {
        prototype: HTMLSelectLanguageElement;
        new (): HTMLSelectLanguageElement;
    };
    interface HTMLTestPageElement extends Components.TestPage, HTMLStencilElement {
    }
    var HTMLTestPageElement: {
        prototype: HTMLTestPageElement;
        new (): HTMLTestPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "home-page": HTMLHomePageElement;
        "kryptand-t": HTMLKryptandTElement;
        "select-language": HTMLSelectLanguageElement;
        "test-page": HTMLTestPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface HomePage {
    }
    interface KryptandT {
        "name"?: string;
        "value"?: any;
    }
    interface SelectLanguage {
    }
    interface TestPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "home-page": HomePage;
        "kryptand-t": KryptandT;
        "select-language": SelectLanguage;
        "test-page": TestPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "kryptand-t": LocalJSX.KryptandT & JSXBase.HTMLAttributes<HTMLKryptandTElement>;
            "select-language": LocalJSX.SelectLanguage & JSXBase.HTMLAttributes<HTMLSelectLanguageElement>;
            "test-page": LocalJSX.TestPage & JSXBase.HTMLAttributes<HTMLTestPageElement>;
        }
    }
}
